baseURL = "https://brosnahan.org/"
locale = "en-US"
title = "The Aerie"

[params]
  tagline = "The stairs are a feature"
  description = "The Aerie — a personal blog at brosnahan.org."

[taxonomies]
  tag = "tags"
  category = "categories"

[pagination]
  pagerSize = 20
